language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - npm run build

deploy:
  provider: pages
  cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master

notifications:
  email: false
